name: Periodic deploy
on:
  schedule:
    - cron: '0 0 1/30 * *' # every 30 days
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy hook
        run: curl -X POST "${{ secrets.DEPLOY_HOOK }}"
